# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d355003d0e1a3688d40f0e690c8947310ecee5b62b76e5e0d9e92905ef956ca99e2f8e2194aa43c1102264bb22ab8376f83d80200355d317a5e0d698d2c2eb53

test:
  secret_key_base: 37fac3a3328bc32d2fb37aad01ed28777e41e3844d566990624fb980d19ea0709d40bbba999fd7a7a76f3e1490224e503f9b5c321315a8200fd0842f17ba4982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
